{
 "title": "Controller Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Control Extenders",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "title": "Control Extenders", "type": "tcpnode-controller-panel", "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 } }
   ]
  },
  { "title": "DIGITAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "DI Total Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "digital",
     "query": "SELECT count(\"di1Status\") FROM \"digital\" WHERE (\"extenderId\" = '256' AND \"di1Status\" > 0) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "extenderId", "operator": "=", "value": "256" }
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "digital",
     "query": "SELECT \"di1Status\", \"di2Status\", \"di3Status\" FROM \"digital\" WHERE (\"extenderId\" = '256') AND $timeFilter",
     "select": [
      [
       { "params": [ "di1Status" ], "type": "field" }
      ],
      [
       { "params": [ "di2Status" ], "type": "field" }
      ],
      [
       { "params": [ "di3Status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "extenderId", "operator": "=", "value": "256" }
     ]
    }
   ]
  },
  {
   "title": "DI_1 'LOW' Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "digital",
     "query": "SELECT count(\"di1Status\") FROM \"digital\" WHERE (\"extenderId\" = '256' AND \"di1Status\" > 0) AND $timeFilter",
     "select": [
      [
       { "params": [ "di1Status" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "extenderId", "operator": "=", "value": "256" },
      { "condition": "AND", "key": "di1Status", "operator": "<", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "digital",
     "query": "SELECT \"di1Status\", \"di2Status\", \"di3Status\" FROM \"digital\" WHERE (\"extenderId\" = '256') AND $timeFilter",
     "select": [
      [
       { "params": [ "di1Status" ], "type": "field" }
      ],
      [
       { "params": [ "di2Status" ], "type": "field" }
      ],
      [
       { "params": [ "di3Status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "extenderId", "operator": "=", "value": "256" }
     ]
    }
   ]
  },
  {
   "title": "DI_2 'LOW' Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "digital",
     "query": "SELECT count(\"di1Status\") FROM \"digital\" WHERE (\"extenderId\" = '256' AND \"di1Status\" > 0) AND $timeFilter",
     "select": [
      [
       { "params": [ "di2Status" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "extenderId", "operator": "=", "value": "256" },
      { "condition": "AND", "key": "di2Status", "operator": "<", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "digital",
     "query": "SELECT \"di1Status\", \"di2Status\", \"di3Status\" FROM \"digital\" WHERE (\"extenderId\" = '256') AND $timeFilter",
     "select": [
      [
       { "params": [ "di1Status" ], "type": "field" }
      ],
      [
       { "params": [ "di2Status" ], "type": "field" }
      ],
      [
       { "params": [ "di3Status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "extenderId", "operator": "=", "value": "256" }
     ]
    }
   ]
  },
  {
   "title": "DI_3 'LOW' Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "digital",
     "query": "SELECT count(\"di3Status\") FROM \"digital\" WHERE (\"extenderId\" = '256' AND \"di3Status\" > 0) AND $timeFilter",
     "select": [
      [
       { "params": [ "di3Status" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "extenderId", "operator": "=", "value": "256" },
      { "condition": "AND", "key": "di3Status", "operator": "<", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "DI - 256",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "digital",
     "select": [
      [
       { "params": [ "di1Status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DI_1" ], "type": "alias" }
      ],
      [
       { "params": [ "di2Status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DI_2" ], "type": "alias" }
      ],
      [
       { "params": [ "di3Status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DI_3" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "extenderId", "operator": "=", "value": "256" }
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "digital",
     "query": "SELECT \"di1Status\", \"di2Status\", \"di3Status\" FROM \"digital\" WHERE (\"extenderId\" = '256') AND $timeFilter",
     "select": [
      [
       { "params": [ "di1Status" ], "type": "field" }
      ],
      [
       { "params": [ "di2Status" ], "type": "field" }
      ],
      [
       { "params": [ "di3Status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "extenderId", "operator": "=", "value": "256" }
     ]
    }
   ]
  }
 ]
}